import '@/app/cs/Global.css';
import { inter} from "@/app/cs/Font";
import Header from "./about/Header";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
      <body className={`${inter.className}antianlised`} >{children}</body>
      
    </html>
  )
}
